#' Generate impact ratings for players
#'
#' Generates a data frame of calculated impact value for each player and lists
#' their IGN, team, total impact, and matches played.
#'
#' @param rpsdf The round player stats data frame
#' @param namedf The data frame generated by id_to_name()
#' @return A data frame with 5 columns
#' @examples
#' impactValues <- get_impact(Champs22RPS, champsNames)
#' head(impactValues)
#' @references \url{
#' https://www.rib.gg/article/measuring-impact-value-most-impactful-players-of-vct-heading-to-champions}
#' @export
get_impact <- function(rpsdf, namedf){
  rps_igns <- match(rpsdf$playerId, namedf$playerId)
  rps_ids <- match(rpsdf$teamId, namedf$teamId)

  impact <- rpsdf %>% mutate(playerIgn = ifelse(is.na(rps_igns), 0,
                                                namedf$playerIgn[rps_igns]),
                             teamName = ifelse(is.na(rps_ids), 0,
                                               namedf$teamName[rps_ids])) %>%
    group_by(playerIgn, teamName) %>%
    summarise(impactValue = (
      round( (sum(as.numeric(impact)) / n_distinct(matchId))*100, 2)),
      totalImpact = round( sum(as.numeric(impact)), 2 ),
      matchesPlayed = n_distinct(matchId)
    )

  return(impact)
}
